name: Build and Benchmark

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install base dependencies
      run: |
        brew install cmake
        brew install conan

    - name: Cache Conan packages
      uses: actions/cache@v4
      with:
        path: ~/.conan2
        key: ${{ runner.os }}-conan-${{ hashFiles('**/conanfile.py') }}
        restore-keys: |
          ${{ runner.os }}-conan-

    - name: Run bootstrap script
      run: |
        chmod +x ./bootstrap.sh
        ./bootstrap.sh

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Run benchmarks
      run: |
        cd build
        ./benchmark/matrix_benchmark